### ISSUE TITLE
cytoscape.js-elk / web worker dependency

### ISSUE THREAD

**Issue by j-barata** [cytoscape/cytoscape.js-elk#10]
In the elkjs documentation it is said :

> A warning is raised if one requests a web worker without having installed the package. elkjs falls back to the non-Web Worker version in that case.

But when I try to do so, using cytoscape.js-elk, I get an error :

`Failed to compile.
<path>/node_modules/elkjs/lib/main.js
Module not found: Can't resolve 'webworker-threads' in '<path>\node_modules\elkjs\lib'`

**Comment by Remimstr** [comment]
This is fixed by #5 but it seems as though the code in the npm registry has not been updated yet. As a workaround, you can install the dependency straight from github, which is what I did because I just wanted to try to library out:

```
yarn add https://github.com/jfstephe/cytoscape.js-elk#master
```
