### ISSUE TITLE
getPos while loop uses incorrect scratch namespace

### ISSUE THREAD

**Issue by WillBeesOn** [cytoscape/cytoscape.js-elk#24]
I have updated to version `1.2.2` but I'm finding that I'm encountering an error in the `getPos` function of `layout.js`. 

I believe the issue stems from this PR: https://github.com/cytoscape/cytoscape.js-elk/pull/22/files which was changed to use a non-existent "klay" scratch namespace. Trying to get the scratch of "klay" returns `undefined` which causes `getPos` to error out.

It doesn't seem like the "klay" scratch is set anywhere either, so I believe this to be a defect.

I would fix it myself but I don't have write access to the repo.

**Comment by akx** [comment]
This is fixed in #15 (1c9bf0fb625e790050f7adaf9fb0f915c104b5e8)...
