### ISSUE TITLE
Nodes Alignment Fails in this module.

### ISSUE THREAD

**Issue by SatishChandraPalakoti** [cytoscape/cytoscape.js-elk#27]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/9092073/111053576-be7f6180-8419-11eb-84fd-c88cbb9d863b.png">

All the nodes are in one place overlapping each other.

**Comment by maxkfranz** [comment]
@akx, might this be related to #15 where worker support was added?

**Comment by maxkfranz** [comment]
@SatishChandraPalakoti, please provide a reproducible example to help @akx.
