### ISSUE TITLE
Move ELK layout to webworker?

### ISSUE THREAD

**Issue by saulshanabrook** [cytoscape/cytoscape.js-elk#34]
Is it possible to have this library use a webworker for the ELK layout instead of doing it on the main thread?

I see that ELK JS has a way to be instantiated with a webworker, but I am not sure how to use that with this library: [https://github.com/kieler/elkjs#browser.](https://github.com/kieler/elkjs#browser.)

**Comment by maxkfranz** [comment]
Webworkers still don't work well with build tools like Webpack, as far as I know.  If you are able to build a workaround, you're welcome to include it in a PR here.

**Comment by saulshanabrook** [comment]
I have ended up manually doing the ELK layout before passing the nodes to Cytoscape, so that I have more control over scheduling and caching. So I was able to copy the webworker file directly then refer to it: https://github.com/saulshanabrook/editor/blob/d58ff591d0a865f1fd3c8c4b1aba10af2b4717ec/src/features/dataflow/layoutSlice.ts#L28-L33 https://github.com/saulshanabrook/editor/blob/d58ff591d0a865f1fd3c8c4b1aba10af2b4717ec/webpack.config.js#L114-L116

But you are right, I am not sure how I would do it in this library, besides providing your own webpack plugin or showing folks how to set that up, similar to how monaco does it.
