### ISSUE TITLE
Cannot resolve `web-worker` issue in create-react-app

### ISSUE THREAD

**Issue by rk-fsdev** [cytoscape/cytoscape.js-elk#36]
this is what I am doing:
```javascript
import Cytoscape from 'react-cytoscapejs';
const Elk = require('cytoscape-elk');
Cytoscape.use(Elk);
```
this throws the error in compiling,
```
./node_modules/elkjs/lib/main.js
Module not found: Can't resolve 'web-worker' in '/node_modules/elkjs/lib'
```

Can anyone resolve this issue?

**Comment by akx** [comment]
Which version of CRA? Do you have a repo where this can be reproduced?

**Comment by hasanbalci** [comment]
I also got the same error. It seems that the problem comes from [elkjs](https://github.com/kieler/elkjs). Here is a similar issue:  kieler/elkjs#142. For now, I installed web-worker independently and the problem is solved.

**Comment by mapkuff** [comment]
face the same issue. here is what I did to fix it.
first just copy elk-worker.js into public folder or something.
then

```
import Worker from 'web-worker';
const ELK = require('elkjs')
const elk = new ELK({
  workerUrl: '/elk-worker.js', // this should match where you put elk-worker.js in public folder
  workerFactory: workerUrl => new Worker(new URL(workerUrl))
})
```
