### ISSUE TITLE
Options not mapped to props as expected

### ISSUE THREAD

**Issue by Lorenz-N** [cytoscape/cytoscape.js-elk#39]
From the given samples, I would expect that options from http://www.eclipse.org/elk/reference.html get mapped to the elk props, e.g.:

```
layout: {
  elk: {
    direction: 'DOWN',
  },
},
```

instead, it seems that the props have to be named by the subsequent identifier as property key in quotes, after the `org.eclipse.` part (which was also misleading in the current sample - saying `org.eclipse.elk.` can be dropped from the Identifier). So currently it seems to be only working with:

```
layout: {
  elk: {
    'elk.direction': 'DOWN',
  },
},
```
`algorithm` and `noLayout` seems to be the only exceptions (not requiring the elk. prefix and property key in quotes) from what I've figured out so far.

**Comment by maxkfranz** [comment]
This may have been a feature of the wrapped Elk library, and perhaps they don't support it universally.  You're welcome to open up a PR to allow this wrapper to offer universal field name conversions

**Comment by maxkfranz** [comment]
See #40 for @Lorenz-N's PR.  Missed that
