### ISSUE TITLE
Ready for listing?

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-elk#4]
Is this extension production-ready enough to be listed with the other layout extensions?

http://js.cytoscape.org/#extensions/layout-extensions

**Comment by jfstephe** [comment]
Hi,
Possibly. I'm using in production ATM but it's pretty basic and I've not really done much other than the fork. The tests are lacking IMHO, but no worse than before.
Go for it ;-).

**Comment by maxkfranz** [comment]
@jfstephe Would you be open to transferring the repo to the Cytoscape Consortium (`cytoscape`)?  I'd like to ensure that this extension has long-term support.  In the short term, I'd like to possibly add some new features to the extension.  Of course, you'd still have write access to the repo.

**Comment by jfstephe** [comment]
Sure. I sounds good. Just let me know what I have to do and I'll pass it over.

**Comment by maxkfranz** [comment]
Basically it should be these steps: https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

The username in the box should be `cytoscape` for this organisation: https://github.com/cytoscape

Or if it's easier for you, you could add me as an admin to this repo and I can take care of the details.

**Comment by jfstephe** [comment]
Hi,
I don't have permissions to create the repo in cytoscape (the transfer fails). I've added you as a collaborator, so feel free to transfer it.
John

**Comment by maxkfranz** [comment]
i accepted the invitation, but I think I need higher permissions within this repo to move it over.

**Comment by jfstephe** [comment]
@maxkfranz - I think I need create repo permissions - I get 'You don’t have the permission to create public repositories on cytoscape'. If you can do that temporarily I'll hopefully transfer it today.

**Comment by jfstephe** [comment]
bosh!

**Comment by maxkfranz** [comment]
It looks like it went through.  You should have r/w permissions for cytoscape/cytoscape.js-elk
